#!/usr/bin/env ruby
# frozen_string_literal: true

# 最大列数を定める(今回は最大3列とす)
MAX_VARIABLE_COLUMNS = 3

# 取得するファイル一覧データを定数にする
FILE_NAMES = Dir.glob('*')

# 表記乱れを防ぐため24字以上の文字列が含まれる場合は1列で表示させる
def display_in_1_column
  FILE_NAMES
end

# すべての文字列が23字以下の場合はMAX_VARIABLE_COLUMNSに設定した列数で表示させる
def display_in_multiple_columns
  # 出力時の行数
  number_of_lines = FILE_NAMES.size / MAX_VARIABLE_COLUMNS + 1

  # 余ってしまう行(余白)に対し要素(nil)を補充し整形に必要な配列を用意
  list_filled_with_blanks = FILE_NAMES + Array.new(number_of_lines * MAX_VARIABLE_COLUMNS - FILE_NAMES.size, nil)

  # 3列に表示させるため配列を分割する
  separated_list = list_filled_with_blanks.each_slice(number_of_lines).to_a

  # 横に展開したときに縦に意図した並び(昇順)が実現できるように配列を変更する。
  (separated_list[0]).zip(separated_list[1], separated_list[2]).map do |n|
    n.map { |num| num.to_s.ljust(24) }.join
  end
end

# 24以上の文字列が含まれるかどうかでレイアウトを決める。
if FILE_NAMES.any? { |s| s.length >= 24 }
  puts display_in_1_column
else
  puts display_in_multiple_columns
end
